// AUTO-GENERATED by Trivial from src/trivial.manifest.json — DO NOT EDIT.
// Regenerated whenever the manifest is saved (Data app, Trio, or a direct edit).
// No manifest yet: declare tables in src/trivial.manifest.json when the app needs data and
// their row types appear here on the next save.

export interface Tables {}

/** Runtime column metadata per table (drives in-app helpers; safe to ignore). */
export const TABLES = {} as const;
