// AUTO-GENERATED by Trivial from src/trivial.manifest.json — DO NOT EDIT.
// Regenerated whenever the manifest is saved (Data app, Trio, or a direct edit).
// Delete a table from the manifest and its types disappear here on the next save.

export interface EntriesRow {
  id: number;
  created_by: string;
  content: string | null;
  created_at: string;
}

export interface Tables {
  entries: EntriesRow;
}

/** Runtime column metadata per table (drives in-app helpers; safe to ignore). */
export const TABLES = {
  entries: { access: "owner", columns: {"content":"text"} },
} as const;
